<?php

namespace ContainerRwdEY5M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5MhxSDBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5MhxSDB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5MhxSDB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EcoleController::createBook' => ['privates', '.service_locator.hD1_.Vl', 'get_ServiceLocator_HD1_VlService', true],
            'App\\Controller\\EcoleController::deleteBook' => ['privates', '.service_locator.zps3.qj', 'get_ServiceLocator_Zps3_QjService', true],
            'App\\Controller\\EcoleController::getDetailEcole' => ['privates', '.service_locator.VrdVmZ5', 'get_ServiceLocator_VrdVmZ5Service', true],
            'App\\Controller\\EcoleController::getEcolesList' => ['privates', '.service_locator.gnCz0wk', 'get_ServiceLocator_GnCz0wkService', true],
            'App\\Controller\\EcoleController::updateEcole' => ['privates', '.service_locator.T_dXJod', 'get_ServiceLocator_TDXJodService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EcoleController:createBook' => ['privates', '.service_locator.hD1_.Vl', 'get_ServiceLocator_HD1_VlService', true],
            'App\\Controller\\EcoleController:deleteBook' => ['privates', '.service_locator.zps3.qj', 'get_ServiceLocator_Zps3_QjService', true],
            'App\\Controller\\EcoleController:getDetailEcole' => ['privates', '.service_locator.VrdVmZ5', 'get_ServiceLocator_VrdVmZ5Service', true],
            'App\\Controller\\EcoleController:getEcolesList' => ['privates', '.service_locator.gnCz0wk', 'get_ServiceLocator_GnCz0wkService', true],
            'App\\Controller\\EcoleController:updateEcole' => ['privates', '.service_locator.T_dXJod', 'get_ServiceLocator_TDXJodService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EcoleController::createBook' => '?',
            'App\\Controller\\EcoleController::deleteBook' => '?',
            'App\\Controller\\EcoleController::getDetailEcole' => '?',
            'App\\Controller\\EcoleController::getEcolesList' => '?',
            'App\\Controller\\EcoleController::updateEcole' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EcoleController:createBook' => '?',
            'App\\Controller\\EcoleController:deleteBook' => '?',
            'App\\Controller\\EcoleController:getDetailEcole' => '?',
            'App\\Controller\\EcoleController:getEcolesList' => '?',
            'App\\Controller\\EcoleController:updateEcole' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
