<?php

namespace ContainerRwdEY5M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zps3_QjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zps3.qj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zps3.qj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ecole' => ['privates', '.errored..service_locator.zps3.qj.App\\Entity\\Ecole', NULL, 'Cannot autowire service ".service_locator.zps3.qj": it needs an instance of "App\\Entity\\Ecole" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ecole' => 'App\\Entity\\Ecole',
            'em' => '?',
        ]);
    }
}
