<?php

namespace ContainerRwdEY5M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TDXJodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T_dXJod' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T_dXJod'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'EcoleRepository' => ['privates', 'App\\Repository\\EcoleRepository', 'getEcoleRepositoryService', true],
            'currentEcole' => ['privates', '.errored..service_locator.T_dXJod.App\\Entity\\Ecole', NULL, 'Cannot autowire service ".service_locator.T_dXJod": it needs an instance of "App\\Entity\\Ecole" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'EcoleRepository' => 'App\\Repository\\EcoleRepository',
            'currentEcole' => 'App\\Entity\\Ecole',
            'em' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
