<?php

namespace ContainerRwdEY5M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VrdVmZ5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VrdVmZ5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VrdVmZ5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ecole' => ['privates', '.errored..service_locator.VrdVmZ5.App\\Entity\\Ecole', NULL, 'Cannot autowire service ".service_locator.VrdVmZ5": it needs an instance of "App\\Entity\\Ecole" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'ecole' => 'App\\Entity\\Ecole',
            'serializer' => '?',
        ]);
    }
}
