<?php

namespace ContainerRwdEY5M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEcoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T_dXJod.App\Entity\Ecole' shared service.
     *
     * @return \App\Entity\Ecole
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.T_dXJod": it needs an instance of "App\\Entity\\Ecole" but this type has been excluded in "config/services.yaml".');
    }
}
