@startuml connexion inscription

title inscription connexion

|#orange|user|
start
fork
:s'inscrire;
fork again 
:se connecter;
end fork

|#lightGreen|serveur|
:affiche page connexion;
|user|
repeat
if (se connecter ou s'inscrire) then (se connecter) 

:se connecter;
repeat
fork
:entrer mail;
fork again
:entrer mot de passe;
end fork
:valider connexion;
backward: réessayer mot de passe;
repeatwhile (mot de passe correct) is (non) not (oui)


else (s'incrire) 
|serveur|
:affiche cadre inscription;

|user|

:s'incrire;
fork
:entrer nom;
fork again
:entrer prénom;
fork again
:entrer mail;
fork again
:entrer mot de passe;
:confirmer mot de passe;
end fork
:valider inscription;
endif
backward :retour se connecter;
repeat while (incription ok)

:valider;
:connexion;
|serveur|
:affiche page d'accueil;

end


@enduml

