@startuml usecase


title = "useCase eduZouzou"

left to right direction


actor superAdmin as sa #red

    actor admin as a #blue
    actor enseignant as ens #green
    actor parent as p #Coral
    actor elève as e #pink



    package superAdmin as packsa {
        useCase "ajouter une école" as addSchool #red
        useCase "modifier une école" as upSchool #red
        useCase "supprimer une école" as delSchool #red
        useCase "gestion des admins" as gesAd #Green
        useCase "ajouter admin" as addAdm #lightGreen
        useCase "supprimer admin" as delAdm #lightGreen

sa-->packsa #line:red;line.dashed;text:red
gesAd -->addAdm :extend
gesAd -->delAdm :extend

    }


    package admin as packa {
        useCase "statistiques et rapports" as stats #LightPink
        useCase "analyser données utilisation" as aDataUse #LightPink
        useCase "analyser performances élèves" as aPerfEl #LightPink
        useCase "analyser participation Activités" as aParta #LightPink
        useCase "gestion des comptes" as gestCompte #LightCoral
        useCase "ajouter compte" as addCompte #Coral
        useCase "supprimer compte" as delCompte #Coral

a-up->packa #blue;line.dashed;text:blue

gestCompte --> addCompte : extend
gestCompte --> delCompte : extend

stats --> aDataUse :extend
stats --> aPerfEl :extend
stats --> aParta :extend


    }

package enseignant  as packens{
        useCase "ajouter une classe" as addClass #LightBlue
        useCase "modifier une classe" as upClass #LightBlue
        useCase "supprimer une classe" as delClass #LightBlue
        useCase "ajouter un cours" as addcours #LightGreen
        useCase "ajouter descriptions" as descr #Green
        useCase "ajouter documents" as doc #Green
        useCase "ajouter videos" as video #Green
        useCase "ajouter ressources supplémentaires" as ressource #Green

addcours --> descr :extends
addcours --> doc :extends
addcours --> video :extends
addcours --> ressource :extends

ens-->packens  #green;line.dashed;text:green 

}



package "parents" as packp{
usecase "messages" as mess #orange
usecase "messagerie" as tchat #orange
    usecase inscription as ins #LightGray 
    usecase "gestion du Profil" as gesProf #LightGray 

p->packp #coral;line.dashed;text:coral
tchat-->mess :extend

}


 package "élèves" as packel{
 usecase "cours" as cours #LightSeaGreen
 usecase "activités" as act #LightSeaGreen
 usecase "resultat" as res #LightSeaGreen
 usecase "compétences" as comp #LightSeaGreen


e-->packel #DarkMagenta;line.dashed;

 }

    useCase connexion as connect #Violet



a <|---sa  #line:lightgray;line.bold;text:lightgray
ens <|---a  #line:lightgray;line.bold;text:lightgray
p<|---ens  #line:lightgray;line.bold;text:lightgray
e<|---p  #line:lightgray;line.bold;text:lightgray



ins <..connect :includes
packsa ..> connect : includes 
packa ..> connect : includes 
packens ..> connect : includes 
packel ..> connect : includes 


@enduml


