@startuml
title "Diagramme de classe ÉduZouzou"
!theme crt-green

class E as "Ecole"{
    nom : string
    adresse: string
    telephone: string
    email: string
}

class P as "Parent" {
    nom : string
    prenom: string
    email: string
    motDePasse: string
    adresse: string
    telephone: string
}

class En as "Enfant" {
    nom : string
    prenom: string
    dateDeNaissance: date
}

class Es as "Enseignant" {
    droitsSupplementaires: string
}

class Ad as "Administrateur" {
    droitsSupplementaires: string
}

class SA as "Super Administrateur" {
    privileges: string
}

class R as "Ressource" {
    type: string
    nom : string
}

class A as "Activité" {
    type: string
    nom : string
    description: string
}

class C as "Cours" {
    description: string
    document: string
    video: string
    ressources sup : string
}

class Cl as "Classe" {
    niveau: string
    anneeScolaire: date
}

class M as "Messagerie" {
    messages: string
}

class Mess as "Message" {
    message: string
    destinataire: string
    expediteur: string
}


E "1" -- "n" P :  relation
E "1" -- "n" En : est inscrit
E "1" -- "n" Es : enseigne
En "1" -- "n" P : est le parent de
Cl "1" -- "n" En : est composée de
Cl "n" -- "n" Es : est enseignée par
Es "n" -- "n" R : ajoute
R "1" -- "n" A : est composée de
R "n" -- "n" C : se compose de
En "n" -- "n" R : accéde à

Es --|> P : hérite de
Ad --|> Es : hérite de
SA --|> Ad : hérite de

Ad "1" -- "1" E : est responsable d'une
SA "1" - "n" E : gère plusieurs
M "1" -- "n" Mess : contient
P "1" -- "n" M : utilise
Es "1" -- "n" M : accède à

@enduml