<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErviIYx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErviIYx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErviIYx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErviIYx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerErviIYx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ErviIYx',
    'container.build_id' => 'b782aa1d',
    'container.build_time' => 1724855093,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErviIYx');
