<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZhM8BTy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZhM8BTy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZhM8BTy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZhM8BTy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZhM8BTy\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZhM8BTy',
    'container.build_id' => '16185edf',
    'container.build_time' => 1724222199,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZhM8BTy');
