<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container82jhBUT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container82jhBUT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container82jhBUT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container82jhBUT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container82jhBUT\App_KernelDevDebugContainer([
    'container.build_hash' => '82jhBUT',
    'container.build_id' => 'f528a2b4',
    'container.build_time' => 1722252361,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container82jhBUT');
