nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ["*"]
    allow_headers: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["*"]
      allow_headers: ["*"]
      allow_methods: ["GET", "POST", "PUT", "DELETE"]
      max_age: 3600
