nelmio_cors:
<<<<<<< HEAD
  defaults:
    allow_credentials: false
    allow_origin: ["*"]
    allow_headers: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["*"]
      allow_headers: ["*"]
      allow_methods: ["GET", "POST", "PUT", "DELETE"]
      max_age: 3600
=======
    defaults:
        origin_regex: true
        allow_origin: ["http://localhost:4200"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/": null
>>>>>>> frontDylan
