export const VariablesGlobales = {
  matieres: [
    'mathématiques',
    'français',
    'histoire',
    'geographie',
    'art plastique',
    'anglais',
    'EPS',
    'education morale et civique',
    'autre',
  ],
  typeAct: ['devoirs', 'quiz', 'projets', 'événements'],
  typeRC: ['cours CP', 'cours CE1', 'cours CE2', 'cours CM1', 'cours CM2'],
  typeRA: [
    'activité CP',
    'activité CE1',
    'activité CE2',
    'activité CM1',
    'activité CM2',
  ],
  niveauCl: ['CP', 'CE1', 'CE2', 'CM1', 'CM2'],
  roles: ['ROLE_USER', 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN', 'ROLE_PROFESSEUR'],
  colorList: ['F9DBA0', 'BBE2EA', 'A7B2FB', 'FBB0A7', 'F9AAB8', 'F2A6FD'],
};
